# Gradle JVM 参数：UTF-8 保证中文字符串/资源不乱码
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# AndroidX
android.useAndroidX=true
# 非传递 R 类：每个模块只生成自己的资源 ID，编译更快、包更小
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official
